# Generated by Django 6.0 on 2026-02-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_play_image_alter_ticket_unique_together"),
    ]

    operations = []
